name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: somaz94/compress-decompress@v1.0.5
      with:
        command: compress
        source: merge-work.sh
        format: tgz
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "*.tgz"
        makeLatest: true
